apiVersion: apps/v1
kind: Deployment
metadata:
  name: ragservice
  labels:
    app: ragservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ragservice
  template:
    metadata:
      labels:
        app: ragservice
    spec:
      containers:
        - name: ragservice
          image: prabal864/livereconai:ragservice-0.1
          ports:
            - containerPort: 9000
          
---

apiVersion: v1
kind: Service
metadata:
  name: ragservice
spec:
  selector:
    app: ragservice
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: LoadBalancer
